# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b93fc989c91073ee22a3c1d8569694de40356487b85f8cceb3e75609e7a83d1fca8e48361631f4f1db6d2b63b2949f10462096e3c3fa2cdf71f34df2080bb16f

test:
  secret_key_base: aa4cb4865eaf82069b6dbbe93170ea7188e5c1d0176de8690ab3b8f478c6bb8ce9f884f09ff2c5f3081328b677bf5d74e31e0f3b4f04efaeb3eb26397ddf736b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
